feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix2014 #[phoenix2014, phoenix2014-T, CSL-Daily, CSL]
# dataset: phoenix14-si5
num_epoch: 40
work_dir: ./work_dir/baseline/
batch_size: 2
random_seed: 0
test_batch_size: 2
num_worker: 10
device: 0,1
log_interval: 10000
eval_interval: 1
save_interval: 5
# python in default
evaluate_tool: sclite
loss_weights:
  SeqCTC: 1.0
  # VAC
  ConvCTC: 1.0
  Dist: 25.0
  #Direct: 1.0
#load_weights: ''

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 20, 30]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0  # 0-1 represents ratio, >1 represents absolute value
  input_size: 224

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: ViT-B/16 #resnet18, RN50, ViT-B/16, ViT-L/14, ViT-L/14@336px
  conv_type: 2
  use_bn: 1
  # SMKD
  share_classifier: True
  weight_norm: True
